id: opecha:P000296
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18292
  title: བོད་ཀྱི་གནའ་རབས་ལོ་རྒྱུས་བདམས་བཏུས་གངས་ལྗོངས་འོད་འབུམ།
  volume:
    a2556f9cef6a4076ae41ef66e128de1e:
      image_group_id: I1KG18418
      title: Volume 1 of bod kyi gna' rabs lo rgyus bdams btus gangs ljongs 'od 'bum/
      volume_number: 1
      total_pages: 274
  author: ''
ebook_metadata:
  title: བོད་ཀྱི་གནའ་རབས་ལོ་རྒྱུས་བདམས་བཏུས་གངས་ལྗོངས་འོད་འབུམ།
  author: ''
  sku: P000296
  cover: cover.jpg
  layers:
  - pagination
