id: P000296
initial_creation_type: ocr
created_at: 10/03/2020
last_modified_at: 2021-12-16 15:32:35.052513
source_metadata:
  id: bdr:W1KG18292
  title: བོད་ཀྱི་གནའ་རབས་ལོ་རྒྱུས་བདམས་བཏུས་གངས་ལྗོངས་འོད་འབུམ།
  author: ''
  volumes:
    a2556f9cef6a4076ae41ef66e128de1e:
      image_group_id: I1KG18418
      title: Volume 1 of bod kyi gna' rabs lo rgyus bdams btus gangs ljongs 'od 'bum/
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
